/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Qu0UfWMzknw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Spinner() {
  return (
    <div className="flex items-center justify-center h-screen">
      <div className="w-12 h-12 rounded-full border-4 border-gray-300 border-t-gray-900 animate-spin dark:border-gray-600 dark:border-t-gray-400 shadow-lg shadow-gray-300/50 dark:shadow-gray-800/50" />
    </div>
  )
}
